"""add_voice_profiles_and_assigned_voice_id

Revision ID: 204de110bebe
Revises: 
Create Date: 2026-03-09 19:34:03.312782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204de110bebe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('assigned_voice_id', sa.String(), nullable=True))
    op.add_column('operators', sa.Column('voice_profiles', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operators', 'voice_profiles')
    op.drop_column('customers', 'assigned_voice_id')
    # ### end Alembic commands ###
